
version: '3.8'

services:
  symfony:
    build: ./symfony-app
    container_name: symfony-app
    ports:
      - "8010:80"
    volumes:
      - ./symfony-app:/var/www/html
    networks:
      - backend-net

  koa:
    build: ./koa-app
    container_name: koa-app
    ports:
      - "8002:3000"
    volumes:
      - ./koa-app:/usr/src/app
    working_dir: /usr/src/app
    command: node index.js
    networks:
      - backend-net

  fastapi:
    build: ./fastapi-app
    container_name: fastapi-app
    ports:
      - "8003:8000"
    volumes:
      - ./fastapi-app:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - backend-net

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony
      - koa
      - fastapi
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
